---
- name: Add key, for docker repository
  apt_key:
    id: 0EBFCD88
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker engine
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes  
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
    - docker-compose

- name: get user info
  getent:
    database: passwd
    key: "{{ uid_default }}"

- name: Adding existing user to group 
  user:
    name: "{{ item.key}}"
    groups: [docker]
    append: yes
  with_dict:
  - "{{ getent_passwd }}"