---
- name: install miscellaneous packages
  apt:
    name: "{{ item }}"
  loop: "{{ miscellaneous_packages_list }}"

- name: install miscellaneous snaps
  snap:
    name: "{{ item }}"
    classic: true
  loop: "{{ miscellaneous_snaps_list }}"