- name: Install zsh shell
  apt:
    name: zsh
    state: present
  when: "'zsh' not in ansible_facts.packages"

- name: check if rules file exists
  stat:
    path: ~/.oh-my-zsh
  register: zsh_download

- name: Download zsh installer
  get_url: 
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/zsh-installer.sh
    mode: 0755
  when: zsh_download.stat.exists == false
  notify: Execute zsh-installer.sh