---
- name: Install All Basic Packages
  apt:
    name: "{{  item  }}"
    state: present
  loop: "{{ packages }}"
  ignore_errors: yes

- name: Load package facts
  package_facts:
    manager: "auto" 

# Generic Softwares 

- name: install chrome browser
  include_tasks: "{{ansible_distribution}}/chrome.yml"
  when: chrome | bool

- name: install virtualbox
  include_tasks: "{{ansible_distribution}}/virtualbox.yml"
  when: virtualbox | bool

- name: install zsh shell
  include_tasks: "{{ansible_distribution}}/zsh.yml"
  when: zsh | bool

- name: install miscellaneous packages
  include_tasks: "{{ansible_distribution}}/miscellaneous_packages.yml"
  when: miscellaneous_packages | bool

- name: install display configuration tools
  include_tasks: "{{ansible_distribution}}/desktop_config.yml"
  when: desktop_config | bool

## Devops Tools

- name: install vscode
  include_tasks: "{{ansible_distribution}}/vscode.yml"
  when: vscode | bool

- name: install Kubernetes Tools
  include_tasks: "{{ansible_distribution}}/k8s_tools.yml"
  when: k8s_tools | bool

- name: install docker enginer
  include_tasks: "{{ansible_distribution}}/docker.yml"
  when: docker | bool

- name: install aws cli
  include_tasks: "Extas/aws.yml"
  when: aws | bool

- name: install gcloud cli #TODO
  include_tasks: "Extas/gcloud.yml"
  when: gcloud | bool

- name: install terraform #TODO
  include_tasks: "Extas/terraform.yml"
  when: terraform | bool